version: '3.4' # docker compose version

services:
  # container name
  internal-server:
    # stdin_open: true 
    # tty: true
    build:
      context: .
      dockerfile: .
    image: love_con:latest
    container_name: love_8000
    volumes:
      - .:app
    working_dir: /app
    entrypoint: ["python3.9", "app.py"]
    ports:
      - "8000:8000"
